version: '3.8'

services:
  redis-master:
    container_name: redis-master
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: 12345
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data/redis-master:/bitnami/redis/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - ./redis-data/redis-insight:/data